apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          image: your-dockerhub-username/login-service:latest
          ports:
            - containerPort: 3005
          envFrom:
            - secretRef:
                name: login-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: ClusterIP
  selector:
    app: login-service
  ports:
    - port: 3005
      targetPort: 3005
